---
title: "Genetic Data Analysis Manual"
author: Marnin Wolfe
university: Auburn University
department: CSES
---

Welcome to **Genetic Data Analysis (CSES 7160)** at Auburn University.

This course covers statistical and computational foundations for analyzing genetic, genomic, and phenotypic data in crop science, with an emphasis on reproducible workflows using **R, Quarto, GitHub**, and modern mixed-model approaches.

### Key Links

-   **Syllabus:** *See Shared Google Doc* (or Canvas page)
-   **Schedule:** *See Shared Google Doc* (or Canvas page)
-   **Lecture Notes:** *See Shared Google Doc* (or Canvas page)
-   **Course GitHub Repo:** <https://github.com/wolfemd/GeneticDataAnalysisManual>

### Instructor

**Dr. Marnin D. Wolfe**\
Assistant Professor, Quantitative Genetics\
Department of Crop, Soil & Environmental Sciences, Auburn University

### Lessons

-   [Lesson 1 - Reproducible data projects](lessons/1_Quarto.html) - `quarto` / Markdown
-   [Lesson 2 - Linear Models with Matrices](lessons/2_LinearModels.html) - `lm`
-   [Lesson 3 - Intro to Mixed Models](lessons/3_MixedModels.html) - `lmer`
-   [Lesson 4 - More Complex Mixed Models](lessons/4_MoreMixedModels.html) - `asreml`
-   [Lesson 5 - Multivariate and Multi-stage Mixed Models](lessons/5_AdvancedMixedModels.html) - `asreml`


